'use strict';
/* The app icon, drawn rather than committed.

   iOS refuses to build with an empty AppIcon set - "did not have any applicable
   content", which is Xcode's way of saying there is no picture - and it wants
   1024x1024, a size the desktop never generates. Rather than commit a binary
   that would then be a second copy of the artwork to keep in step, this borrows
   the same speaker glyph the desktop draws and renders it at whatever size is
   asked for.

   Android already has icons: Capacitor ships mipmaps in the generated project,
   and they build fine, so nothing here touches them. */
const fs = require('fs');
const path = require('path');
const { canvas, glyph, roundedRect, png } = require('../../scripts/make-icon.js');

function appIcon(size) {
  const c = canvas(size, size);
  /* Same construction as the desktop icon: the blue rounded square with the
     speaker over it, scaled by proportion so it stays crisp. */
  roundedRect(c, size, Math.round(size * 0.22), [47, 109, 246, 255]);
  glyph(c, size, [255, 255, 255, 255], 0.3);
  return png(c);
}

/* iOS asset catalogues take a single 1024 image now; the older per-device sizes
   are generated by Xcode from it. */
const IOS_SET = path.join(__dirname, '..', 'ios', 'App', 'App',
  'Assets.xcassets', 'AppIcon.appiconset');

if (!fs.existsSync(path.dirname(IOS_SET))) {
  console.log('  no ios project here yet - nothing to draw into');
  process.exit(0);
}

fs.mkdirSync(IOS_SET, { recursive: true });
fs.writeFileSync(path.join(IOS_SET, 'AppIcon-512@2x.png'), appIcon(1024));
fs.writeFileSync(path.join(IOS_SET, 'Contents.json'), JSON.stringify({
  images: [{ filename: 'AppIcon-512@2x.png', idiom: 'universal',
    platform: 'ios', size: '1024x1024' }],
  info: { author: 'xcode', version: 1 },
}, null, 2) + '\n');
console.log('  AppIcon-512@2x.png  1024x1024');
